<?php
/***********************************************************************
| Avactis (TM) Shopping Cart software developed by HBWSL.
| http://www.avactis.com
| -----------------------------------------------------------------------
| All source codes & content (c) Copyright 2004-2010, HBWSL.
| unless specifically noted otherwise.
| =============================================
| This source code is released under the Avactis License Agreement.
| The latest version of this license can be found here:
| http://www.avactis.com/license.php
|
| By using this software, you acknowledge having read this license agreement
| and agree to be bound thereby.
|
 ***********************************************************************/
?><?php
define('DATETIME_PERIOD_DISCONTINUITY_DAY', 'DATETIME_PERIOD_DISCONTINUITY_DAY');
define('DATETIME_PERIOD_DAY_THIS',      'DATETIME_PERIOD_DAY_THIS');
define('DATETIME_PERIOD_DAY_PREVIOUS',  'DATETIME_PERIOD_DAY_PREVIOUS');
define('DATETIME_PERIOD_DAY_LAST_10',   'DATETIME_PERIOD_DAY_LAST_10');
define('DATETIME_PERIOD_DAY_LAST_14',   'DATETIME_PERIOD_DAY_LAST_14');
define('DATETIME_PERIOD_DAY_LAST_30',   'DATETIME_PERIOD_DAY_LAST_30');

define('DATETIME_PERIOD_DISCONTINUITY_WEEK', 'DATETIME_PERIOD_DISCONTINUITY_WEEK');
define('DATETIME_PERIOD_WEEK_THIS',     'DATETIME_PERIOD_WEEK_THIS');
define('DATETIME_PERIOD_WEEK_PREVIOUS', 'DATETIME_PERIOD_WEEK_PREVIOUS');
define('DATETIME_PERIOD_WEEK_LAST_2',   'DATETIME_PERIOD_WEEK_LAST_2');
define('DATETIME_PERIOD_WEEK_LAST_4',   'DATETIME_PERIOD_WEEK_LAST_4');
define('DATETIME_PERIOD_WEEK_LAST_10',  'DATETIME_PERIOD_WEEK_LAST_10');
define('DATETIME_PERIOD_WEEK_LAST_30',  'DATETIME_PERIOD_WEEK_LAST_30');

define('DATETIME_PERIOD_DISCONTINUITY_MONTH', 'DATETIME_PERIOD_DISCONTINUITY_MONTH');
define('DATETIME_PERIOD_MONTH_THIS',    'DATETIME_PERIOD_MONTH_THIS');
define('DATETIME_PERIOD_MONTH_PREVIOUS','DATETIME_PERIOD_MONTH_PREVIOUS');
define('DATETIME_PERIOD_MONTH_LAST_2',  'DATETIME_PERIOD_MONTH_LAST_2');
define('DATETIME_PERIOD_MONTH_LAST_4',  'DATETIME_PERIOD_MONTH_LAST_4');
define('DATETIME_PERIOD_MONTH_LAST_6',  'DATETIME_PERIOD_MONTH_LAST_6');
define('DATETIME_PERIOD_MONTH_LAST_12',  'DATETIME_PERIOD_MONTH_LAST_12');
define('DATETIME_PERIOD_MONTH_LAST_10',  'DATETIME_PERIOD_MONTH_LAST_10');

define('DATETIME_PERIOD_DISCONTINUITY_YEAR', 'DATETIME_PERIOD_DISCONTINUITY_YEAR');
define('DATETIME_PERIOD_YEAR_THIS',     'DATETIME_PERIOD_YEAR_THIS');
define('DATETIME_PERIOD_YEAR_PREVIOUS', 'DATETIME_PERIOD_YEAR_PREVIOUS');
define('DATETIME_PERIOD_YEAR_LAST_2',   'DATETIME_PERIOD_YEAR_LAST_2');
define('DATETIME_PERIOD_YEAR_LAST_4',   'DATETIME_PERIOD_YEAR_LAST_4');
define('DATETIME_PERIOD_YEAR_LAST_6',   'DATETIME_PERIOD_YEAR_LAST_6');

define('DATETIME_PERIOD_UNDEFINED', 'DATETIME_PERIOD_UNDEFINED');
define('DATETIME_PERIOD_DISCONTINUITY_UNDEFINED', 'DATETIME_PERIOD_DISCONTINUITY_UNDEFINED');


define('REPORT_PLACEHOLDER_FULL', 'REPORT_PLACEHOLDER_FULL');
define('REPORT_PLACEHOLDER_HALF', 'REPORT_PLACEHOLDER_HALF');

define('REPORT_OUTPUT_AJAX_LOADER','REPORT_OUTPUT_AJAX_LOADER');
define('REPORT_OUTPUT_SIMPLE_AJAX_LOADER','REPORT_OUTPUT_SIMPLE_AJAX_LOADER');
define('REPORT_OUTPUT_CONTENT','REPORT_OUTPUT_CONTENT');

define('DBQUERY_EXPR_SHIFTED_DATETIME','DATE_ADD(%value%, INTERVAL %time_shift% HOUR)');
define('DBQUERY_EXPR_SHIFTED_NOW',     'DATE_ADD(NOW(), INTERVAL %time_shift% HOUR)');

define('TYPE_YEAR', 'TYPE_YEAR');
define('TYPE_MONTH', 'TYPE_MONTH');
define('TYPE_DAY', 'TYPE_DAY');

?>